// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_51pLgzOmy-vlfbf7NEoDyLzEPIIypVU',
    appId: '1:109711596453:web:c3c498d243bff1dfa0e64c',
    messagingSenderId: '109711596453',
    projectId: 'app-psi-b140d',
    authDomain: 'app-psi-b140d.firebaseapp.com',
    storageBucket: 'app-psi-b140d.firebasestorage.app',
    measurementId: 'G-YF8FGYS053',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlp3knVzC9tOiM_Ha1PTOiDdN94dCw0s',
    appId: '1:109711596453:android:c5e27551bac882d4a0e64c',
    messagingSenderId: '109711596453',
    projectId: 'app-psi-b140d',
    storageBucket: 'app-psi-b140d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ2qKHgeAM797qTiScgKn9jS5CLpkqPV0',
    appId: '1:109711596453:ios:d6bdb8ad94aabd66a0e64c',
    messagingSenderId: '109711596453',
    projectId: 'app-psi-b140d',
    storageBucket: 'app-psi-b140d.firebasestorage.app',
    iosBundleId: 'com.example.psi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ2qKHgeAM797qTiScgKn9jS5CLpkqPV0',
    appId: '1:109711596453:ios:d6bdb8ad94aabd66a0e64c',
    messagingSenderId: '109711596453',
    projectId: 'app-psi-b140d',
    storageBucket: 'app-psi-b140d.firebasestorage.app',
    iosBundleId: 'com.example.psi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_51pLgzOmy-vlfbf7NEoDyLzEPIIypVU',
    appId: '1:109711596453:web:8c1c2d0ee17cd214a0e64c',
    messagingSenderId: '109711596453',
    projectId: 'app-psi-b140d',
    authDomain: 'app-psi-b140d.firebaseapp.com',
    storageBucket: 'app-psi-b140d.firebasestorage.app',
    measurementId: 'G-7EG6RV9X3C',
  );
}
